name: Check Release Notes
author: bertpluymers
description: Check if Release Notes is part of PR & has version number in it

inputs:
    uv_version:
        required: true
        description: "Version of UV to be used."
    git_ref:
        required: true
        description: "git ref that triggered workflow"


runs:
  using: "composite"
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ inputs.uv_version }}

      - name: Check if release notes have changed
        shell: bash
        run: |
          git fetch origin ${{ inputs.git_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ inputs.git_ref }}...HEAD)
          if echo "$CHANGED_FILES" | grep -q "RELEASE_NOTES.md"; then
            echo "RELEASE_NOTES.md found in diff --> OK"
          else
            echo "RELEASE_NOTES.md NOT found in diff --> FAIL"
            exit -1
          fi

      - name: Check if release notes contain current version
        shell: bash
        run: |
          CURRENT_VERSION=$(uv version --short)
          if grep -q "$CURRENT_VERSION" RELEASE_NOTES.md; then
            echo "RELEASE_NOTES.md contains current version $CURRENT_VERSION --> OK"
          else
            echo "RELEASE_NOTES.md does NOT contain current version $CURRENT_VERSION --> FAIL"
            exit -1
          fi