"""Section C holds the value-dependent sub-cases.

Redundancy probes (`reinforces=True`) sit directly under the probe they reinforce and pin
both sides of each value-dependent boundary.
"""

import math

from counted_float import CountedFloat

from ._row import (
    I_EXP10,
    I_EXPONENT_CHAIN,
    I_FMA,
    I_IDENTITY_FOLDS,
    I_LOG_BASE,
    I_LOOPS,
    I_MEASUREMENT,
    I_RECIPROCAL,
    R_ENDINGS,
    R_PORT,
    R_RECORDS,
    R_RULES,
    GoldenRow,
)

CF = CountedFloat

ROWS: list[GoldenRow] = [
    # Operators, folds, and unary.
    GoldenRow("C1", "cf + cf", lambda num: num(1.0) + num(2.0), {"ADD": 1}, CF, cites=(R_RULES,)),
    GoldenRow("C2", "cf - cf", lambda num: num(1.0) - num(2.0), {"SUB": 1}, CF, cites=(R_RULES,)),
    GoldenRow("C3", "cf * cf", lambda num: num(1.5) * num(2.0), {"MUL": 1}, CF, cites=(R_RULES,)),
    GoldenRow("C4", "cf / 3.0", lambda num: num(6.0) / 3.0, {"DIV": 1}, CF, cites=(R_RULES,)),
    GoldenRow("C5", "cf * 1.0 folds", lambda num: num(3.0) * 1.0, {}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow("C6", "cf * -1.0 sign flip", lambda num: num(3.0) * -1.0, {"MINUS": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow("C7", "cf * 0.0 near-miss", lambda num: num(3.0) * 0.0, {"MUL": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow("C7", "cf * -0.0 near-miss", lambda num: num(3.0) * -0.0, {"MUL": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow(
        "C8",
        "cf / +-8.0 reciprocal fold",
        lambda num: (num(3.0) / 8.0, num(3.0) / -8.0),
        {"MUL": 2},
        (CF, CF),
        cites=(I_RECIPROCAL,),
    ),
    GoldenRow(
        "C8",
        "reciprocal bound at 2**-1023 / 2**-1024",
        lambda num: (num(1.0) / 2.0**-1023, num(1.0) / 2.0**-1024),
        {"DIV": 1, "MUL": 1},
        (CF, CF),
        cites=(I_RECIPROCAL,),
    ),
    GoldenRow(
        "C8",
        "reciprocal bound holds at -(2**-1023)",
        lambda num: num(1.0) / -(2.0**-1023),
        {"MUL": 1},
        CF,
        cites=(I_RECIPROCAL,),
        reinforces=True,
    ),
    GoldenRow("C9", "cf / 1.0 folds", lambda num: num(3.0) / 1.0, {}, CF, cites=(I_RECIPROCAL,)),
    GoldenRow("C10", "cf / -1.0 sign flip", lambda num: num(3.0) / -1.0, {"MINUS": 1}, CF, cites=(I_RECIPROCAL,)),
    GoldenRow("C11", "cf + (-0.0) folds", lambda num: num(3.0) + (-0.0), {}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow(
        "C11",
        "(-0.0) + cf folds reflected",
        lambda num: (-0.0) + num(3.0),
        {},
        CF,
        cites=(I_IDENTITY_FOLDS,),
        reinforces=True,
    ),
    GoldenRow("C12", "cf + 0.0 counts", lambda num: num(3.0) + 0.0, {"ADD": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow(
        "C12",
        "0.0 + cf counts reflected",
        lambda num: 0.0 + num(3.0),
        {"ADD": 1},
        CF,
        cites=(I_IDENTITY_FOLDS,),
        reinforces=True,
    ),
    GoldenRow("C13", "cf - 0.0 folds", lambda num: num(3.0) - 0.0, {}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow("C14", "cf - (-0.0) counts", lambda num: num(3.0) - (-0.0), {"SUB": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow("C15", "0.0 - cf counts", lambda num: 0.0 - num(3.0), {"SUB": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow(
        "C16", "(-0.0) - cf sign flip", lambda num: (-0.0) - num(3.0), {"MINUS": 1}, CF, cites=(I_IDENTITY_FOLDS,)
    ),
    GoldenRow("C17", "-cf", lambda num: -num(3.0), {"MINUS": 1}, CF, cites=(R_RULES,)),
    GoldenRow("C18", "+cf free but counted type", lambda num: +num(3.0), {}, CF, cites=(R_PORT,)),
    GoldenRow("C19", "abs(cf)", lambda num: abs(num(-3.0)), {"ABS": 1}, CF, cites=(R_RULES,)),
    # Floored division family.
    GoldenRow("C20", "cf // 3.0", lambda num: num(7.0) // 3.0, {"DIV": 1, "RND": 1}, CF, cites=(R_RULES,)),
    GoldenRow(
        "C21", "cf // 8.0 reciprocal step", lambda num: num(7.0) // 8.0, {"MUL": 1, "RND": 1}, CF, cites=(I_RECIPROCAL,)
    ),
    GoldenRow("C22", "cf // 1.0", lambda num: num(7.5) // 1.0, {"RND": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow("C23", "cf // -1.0", lambda num: num(7.5) // -1.0, {"MINUS": 1, "RND": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow(
        "C24", "cf % 3.0", lambda num: num(7.0) % 3.0, {"DIV": 1, "MUL": 1, "RND": 1, "SUB": 1}, CF, cites=(R_RULES,)
    ),
    GoldenRow(
        "C24",
        "divmod(cf, 3.0) same price",
        lambda num: divmod(num(7.0), 3.0),
        {"DIV": 1, "MUL": 1, "RND": 1, "SUB": 1},
        (CF, CF),
        cites=(R_RULES,),
    ),
    GoldenRow("C25", "cf % 8.0", lambda num: num(7.0) % 8.0, {"MUL": 2, "RND": 1, "SUB": 1}, CF, cites=(I_RECIPROCAL,)),
    GoldenRow(
        "C25",
        "divmod(cf, 8.0) same price",
        lambda num: divmod(num(7.0), 8.0),
        {"MUL": 2, "RND": 1, "SUB": 1},
        (CF, CF),
        cites=(I_RECIPROCAL,),
    ),
    GoldenRow("C26", "cf % 1.0", lambda num: num(7.5) % 1.0, {"RND": 1, "SUB": 1}, CF, cites=(I_IDENTITY_FOLDS,)),
    GoldenRow(
        "C26",
        "divmod(cf, 1.0) same price",
        lambda num: divmod(num(7.5), 1.0),
        {"RND": 1, "SUB": 1},
        (CF, CF),
        cites=(I_IDENTITY_FOLDS,),
    ),
    GoldenRow(
        "C27", "cf % -1.0", lambda num: num(7.5) % -1.0, {"MINUS": 2, "RND": 1, "SUB": 1}, CF, cites=(I_IDENTITY_FOLDS,)
    ),
    GoldenRow(
        "C27",
        "divmod(cf, -1.0) same price",
        lambda num: divmod(num(7.5), -1.0),
        {"MINUS": 2, "RND": 1, "SUB": 1},
        (CF, CF),
        cites=(I_IDENTITY_FOLDS,),
    ),
    # Round family and comparisons.
    GoldenRow("C28", "round(cf) int exit", lambda num: round(num(2.7)), {"F2I": 1}, int, cites=(R_ENDINGS,)),
    GoldenRow("C29", "round(cf, 0)", lambda num: round(num(2.7), 0), {"RND": 1}, CF, cites=(R_RULES,)),
    GoldenRow(
        "C30", "round(cf, 2)", lambda num: round(num(2.716), 2), {"DIV": 1, "MUL": 1, "RND": 1}, CF, cites=(R_RULES,)
    ),
    GoldenRow(
        "C30",
        "round(cf, -2) same port",
        lambda num: round(num(271.6), -2),
        {"DIV": 1, "MUL": 1, "RND": 1},
        CF,
        cites=(R_RULES,),
        reinforces=True,
    ),
    GoldenRow("C31", "cf < 2.0", lambda num: num(1.0) < 2.0, {"COMP": 1}, bool, cites=(R_ENDINGS,)),
    GoldenRow("C31", "cf == cf", lambda num: num(1.0) == num(1.0), {"COMP": 1}, bool, cites=(R_ENDINGS,)),
    GoldenRow("C31", "cf == 'abc' declines free", lambda num: num(1.0) == "abc", {}, bool, cites=(R_RECORDS,)),
    GoldenRow("C31", "cf < 'abc' raises", lambda num: num(1.0) < "abc", {}, raises=TypeError, cites=(R_RECORDS,)),
    GoldenRow(
        "C32",
        "min(cf, cf, cf) chain",
        lambda num: min(num(3.0), num(2.0), num(1.0)),
        {"COMP": 2},
        CF,
        cites=(R_ENDINGS,),
    ),
    GoldenRow("C33", "min(cf, 2.0) plain wins", lambda num: min(num(3.0), 2.0), {"COMP": 1}, float, cites=(R_ENDINGS,)),
    GoldenRow(
        "C34", "cf.is_integer()", lambda num: num(3.0).is_integer(), {"COMP": 1, "RND": 1}, bool, cites=(R_RULES,)
    ),
    # The pow ladder.
    GoldenRow("C35", "cf ** cf", lambda num: num(3.0) ** num(2.0), {"POW": 1}, CF, cites=(I_EXPONENT_CHAIN,)),
    GoldenRow("C36", "cf ** 0 absorbs plain", lambda num: num(3.0) ** 0, {}, float, cites=(I_EXPONENT_CHAIN,)),
    GoldenRow("C37", "cf ** 1 identity", lambda num: num(3.0) ** 1, {}, CF, cites=(I_EXPONENT_CHAIN,)),
    GoldenRow("C38", "cf ** 2 square", lambda num: num(3.0) ** 2, {"MUL": 1}, CF, cites=(I_EXPONENT_CHAIN,)),
    GoldenRow(
        "C39",
        "chain rungs ** 3 / ** 8 / ** -3",
        lambda num: (num(3.0) ** 3, num(3.0) ** 8, num(3.0) ** -3),
        {"DIV": 1, "MUL": 7},
        (CF, CF, CF),
        cites=(I_EXPONENT_CHAIN,),
    ),
    GoldenRow(
        "C39",
        "chain bound inside at ** 16",
        lambda num: num(3.0) ** 16,
        {"MUL": 4},
        CF,
        cites=(I_EXPONENT_CHAIN,),
        reinforces=True,
    ),
    GoldenRow(
        "C39",
        "chain bound inside at ** -16",
        lambda num: num(3.0) ** -16,
        {"DIV": 1, "MUL": 4},
        CF,
        cites=(I_EXPONENT_CHAIN,),
        reinforces=True,
    ),
    GoldenRow(
        "C39",
        "float-typed exponent ** 5.0 keys by value",
        lambda num: num(3.0) ** 5.0,
        {"MUL": 3},
        CF,
        cites=(I_EXPONENT_CHAIN,),
        reinforces=True,
    ),
    GoldenRow("C40", "cf ** -1 reciprocal", lambda num: num(3.0) ** -1, {"DIV": 1}, CF, cites=(I_EXPONENT_CHAIN,)),
    GoldenRow(
        "C41",
        "cf ** 0.5 / ** -0.5",
        lambda num: (num(3.0) ** 0.5, num(3.0) ** -0.5),
        {"DIV": 1, "SQRT": 2},
        (CF, CF),
        cites=(I_EXPONENT_CHAIN,),
    ),
    GoldenRow(
        "C42",
        "generic POW ** 2.7 / ** 17",
        lambda num: (num(3.0) ** 2.7, num(3.0) ** 17),
        {"POW": 2},
        (CF, CF),
        cites=(I_EXPONENT_CHAIN,),
    ),
    GoldenRow(
        "C42",
        "chain bound outside at ** -17",
        lambda num: num(3.0) ** -17,
        {"POW": 1},
        CF,
        cites=(I_EXPONENT_CHAIN,),
        reinforces=True,
    ),
    GoldenRow("C43", "1.0 ** cf absorbs plain", lambda num: 1.0 ** num(3.0), {}, float, cites=(R_PORT,)),
    GoldenRow("C44", "2 ** cf reduces to EXP2", lambda num: 2 ** num(3.0), {"EXP2": 1}, CF, cites=(I_EXP10,)),
    GoldenRow(
        "C44",
        "2.0 ** cf keys by value",
        lambda num: 2.0 ** num(3.0),
        {"EXP2": 1},
        CF,
        cites=(I_EXP10,),
        reinforces=True,
    ),
    GoldenRow("C45", "10 ** cf prices EXP10", lambda num: 10 ** num(3.0), {"EXP10": 1}, CF, cites=(I_EXP10,)),
    GoldenRow(
        "C45",
        "10.0 ** cf keys by value",
        lambda num: 10.0 ** num(3.0),
        {"EXP10": 1},
        CF,
        cites=(I_EXP10,),
        reinforces=True,
    ),
    GoldenRow("C46", "math.e ** cf generic POW", lambda num: math.e ** num(3.0), {"POW": 1}, CF, cites=(I_EXP10,)),
    GoldenRow(
        "C47",
        "(-2.0) ** cf(0.5) complex exit",
        lambda num: (-2.0) ** num(0.5),
        {},
        complex,
        cites=(R_ENDINGS,),
    ),
    GoldenRow(
        "C47",
        "cf(-2.0) ** cf(0.5) complex exit",
        lambda num: num(-2.0) ** num(0.5),
        {},
        complex,
        cites=(R_ENDINGS,),
    ),
    GoldenRow(
        "C48",
        "math.pow absorbing forms",
        lambda num: (math.pow(num(3.0), 0), math.pow(1.0, num(3.0))),
        {},
        (float, float),
        cites=(I_EXPONENT_CHAIN,),
    ),
    # The log ladder.
    GoldenRow("C49", "log(cf)", lambda num: math.log(num(8.0)), {"LOG": 1}, CF, cites=(I_LOG_BASE,)),
    GoldenRow("C50", "log(cf, 2)", lambda num: math.log(num(8.0), 2), {"LOG2": 1}, CF, cites=(I_LOG_BASE,)),
    GoldenRow("C51", "log(cf, 10)", lambda num: math.log(num(1000.0), 10), {"LOG10": 1}, CF, cites=(I_LOG_BASE,)),
    GoldenRow(
        "C52",
        "log(cf, 3) folded multiplier",
        lambda num: math.log(num(27.0), 3),
        {"LOG": 1, "MUL": 1},
        CF,
        cites=(I_LOG_BASE,),
    ),
    GoldenRow(
        "C53",
        "log base e / base 1/e",
        lambda num: (math.log(num(8.0), math.e), math.log(num(8.0), 1 / math.e)),
        {"LOG": 2, "MINUS": 1},
        (CF, CF),
        cites=(I_LOG_BASE,),
    ),
    GoldenRow(
        "C53",
        "log(cf, 1.0) raises before counting",
        lambda num: math.log(num(8.0), 1.0),
        {},
        raises=ZeroDivisionError,
        cites=(I_LOG_BASE, R_RECORDS),
        reinforces=True,
    ),
    GoldenRow(
        "C54",
        "log(16.0, cf) counted base",
        lambda num: math.log(16.0, num(2.0)),
        {"DIV": 1, "LOG": 1},
        CF,
        cites=(I_LOG_BASE,),
    ),
    GoldenRow(
        "C55",
        "log(cf, cf) both counted",
        lambda num: math.log(num(16.0), num(2.0)),
        {"DIV": 1, "LOG": 2},
        CF,
        cites=(I_LOG_BASE,),
    ),
    # Fma.
    GoldenRow(
        "C56",
        "fma(cf, cf, cf)",
        lambda num: math.fma(num(2.0), num(3.0), num(4.0)),
        {"FMA": 1},
        CF,
        requires="fma",
        cites=(I_FMA,),
    ),
    GoldenRow(
        "C56",
        "fma(cf, 1.0, 4.0) stays fused",
        lambda num: math.fma(num(2.0), 1.0, 4.0),
        {"FMA": 1},
        CF,
        requires="fma",
        cites=(I_FMA,),
    ),
    GoldenRow(
        "C57",
        "fma constant product leaves ADD",
        lambda num: math.fma(2.0, 3.0, num(4.0)),
        {"ADD": 1},
        CF,
        requires="fma",
        cites=(I_FMA,),
    ),
    GoldenRow(
        "C57",
        "fma(2.0, 0.0, cf) +0.0 keeps ADD",
        lambda num: math.fma(2.0, 0.0, num(4.0)),
        {"ADD": 1},
        CF,
        requires="fma",
        cites=(I_FMA, I_IDENTITY_FOLDS),
    ),
    GoldenRow(
        "C58",
        "fma(2.0, -0.0, cf) folds away",
        lambda num: math.fma(2.0, -0.0, num(4.0)),
        {},
        CF,
        requires="fma",
        cites=(I_FMA, I_IDENTITY_FOLDS),
    ),
    # Arity-scaled calls.
    GoldenRow(
        "C59",
        "hypot(cf, cf, cf)",
        lambda num: math.hypot(num(1.0), num(2.0), num(2.0)),
        {"HYPOT": 1, "HYPOT_XARG": 1},
        CF,
        cites=(I_MEASUREMENT,),
    ),
    GoldenRow(
        "C60", "hypot(cf) 1-arg shortcut", lambda num: math.hypot(num(-3.0)), {"ABS": 1}, CF, cites=(I_MEASUREMENT,)
    ),
    GoldenRow(
        "C61",
        "dist 3-D",
        lambda num: math.dist([num(0.0)] * 3, [1.0, 2.0, 2.0]),
        {"DIST": 1, "DIST_XARG": 1},
        CF,
        cites=(I_MEASUREMENT,),
    ),
    GoldenRow(
        "C62",
        "dist 1-D shortcut",
        lambda num: math.dist((num(1.5),), (4.0,)),
        {"ABS": 1, "SUB": 1},
        CF,
        cites=(I_MEASUREMENT,),
    ),
    GoldenRow(
        "C63",
        "sumprod 3 elems",
        lambda num: math.sumprod([num(1.0), num(2.0), num(3.0)], [1.0, 1.0, 1.0]),
        {"SUMPROD": 1, "SUMPROD_XELEM": 1},
        CF,
        requires="sumprod",
        cites=(I_MEASUREMENT,),
    ),
    GoldenRow(
        "C63",
        "sumprod 1 elem base alone",
        lambda num: math.sumprod([num(2.0)], [3.0]),
        {"SUMPROD": 1},
        CF,
        requires="sumprod",
        cites=(I_MEASUREMENT,),
    ),
    # Sequence calls.
    GoldenRow(
        "C64",
        "prod([cf, cf, cf])",
        lambda num: math.prod([num(2.0), num(3.0), num(4.0)]),
        {"MUL": 2},
        CF,
        cites=(I_LOOPS,),
    ),
    GoldenRow(
        "C64", "prod([cf], start=2.0)", lambda num: math.prod([num(3.0)], start=2.0), {"MUL": 1}, CF, cites=(I_LOOPS,)
    ),
    GoldenRow(
        "C64",
        "prod(plain, start=cf)",
        lambda num: math.prod([2.0, 3.0], start=num(4.0)),
        {"MUL": 2},
        CF,
        cites=(I_LOOPS,),
    ),
    GoldenRow(
        "C64",
        "prod([cf, 1.0, -1.0]) no element folds",
        lambda num: math.prod([num(2.0), 1.0, -1.0]),
        {"MUL": 2},
        CF,
        cites=(I_LOOPS,),
    ),
    GoldenRow(
        "C64",
        "prod([2.0, 3.0, cf]) plain prefix priced",
        lambda num: math.prod([2.0, 3.0, num(4.0)]),
        {"MUL": 2},
        CF,
        cites=(I_LOOPS,),
    ),
    GoldenRow(
        "C64",
        "prod([cf] + [1.0]*9) loop price",
        lambda num: math.prod([num(2.0), *([1.0] * 9)]),
        {"MUL": 9},
        CF,
        cites=(I_LOOPS,),
    ),
    GoldenRow(
        "C64",
        "prod([cf]) single element",
        lambda num: math.prod([num(2.0)]),
        {},
        CF,
        cites=(I_LOOPS,),
        reinforces=True,
    ),
    GoldenRow(
        "C65", "builtin sum folds per operator", lambda num: sum([num(1.0)] * 3), {"ADD": 3}, CF, cites=(I_LOOPS,)
    ),
]
