name: Update Splash Image
author: Bert Pluymers
description: Upload the static splash image as a version artifact.

runs:
    using: "composite"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare splash screen
        shell: bash
        run: |
            mkdir -p "./splash"
            cp "./images/splash/splash.webp" "./splash/splash.webp"

      - name: Pass splash to next action
        uses: actions/upload-artifact@v4
        with:
          name: splash
          path: ./splash/
